name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Replace with your desired branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: https://hub.docker.com  # Replace with your Docker registry URL

      - name: Build and push Docker image
        run: |
          docker build -t githubworkflowsetup_1 .
          docker tag githubworkflowsetup_1 https://hub.docker.com/githubworkflowsetup_1
          docker push https://hub.docker.com/githubworkflowsetup_1
